# Generated by Django 5.2 on 2025-05-24 15:38

import Aspirante.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actas_Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=Aspirante.models.actas_upload_to)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosExpedienteDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField()),
                ('archivo', models.FileField(upload_to=Aspirante.models.documento_upload_to)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCambioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_solicitada', models.TextField()),
                ('area', models.TextField(null=True)),
                ('cargo_actual', models.TextField()),
                ('especialidad_solicitada', models.TextField()),
                ('observaciones', models.TextField(null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.TextField(default='Pendiente')),
                ('fecha_resolucion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
