# Generated by Django 5.2 on 2025-05-05 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosExpedienteDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField()),
                ('archivo', models.FileField(upload_to='soportes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('aspirante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='Administrador.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCambioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_solicitada', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.TextField(default='Pendiente')),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='Administrador.aspirante')),
                ('documentos', models.ManyToManyField(to='Aspirante.documentosexpedientedocente')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('aspirante', 'categoria_solicitada'), name='solicitud_unica_por_categoria')],
            },
        ),
    ]
