# Generated by Django 5.2 on 2025-05-10 04:45

import Aspirante.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosExpedienteDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField()),
                ('archivo', models.FileField(upload_to=Aspirante.models.documento_upload_to)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('aspirante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='Administrador.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCambioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_solicitada', models.TextField()),
                ('observaciones', models.TextField(null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.TextField(default='Pendiente')),
                ('fecha_resolucion', models.DateTimeField(auto_now=True)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='Administrador.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Actas_Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=Aspirante.models.actas_upload_to)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('solicitud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspirante.solicitudcambiocategoria')),
            ],
        ),
    ]
