# Generated by Django 5.2 on 2025-05-09 20:40

import Aspirante.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosexpedientedocente',
            name='archivo',
            field=models.FileField(upload_to=Aspirante.models.documento_upload_to),
        ),
        migrations.CreateModel(
            name='Actas_Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=Aspirante.models.actas_upload_to)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('solicitud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspirante.solicitudcambiocategoria')),
            ],
        ),
    ]
