# Generated by Django 5.2 on 2025-05-24 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrador', '0001_initial'),
        ('Aspirante', '0001_initial'),
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actas_tribunal',
            name='miembro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_tribunal', to='RRHH.miembro_tribunal'),
        ),
        migrations.AddField(
            model_name='documentosexpedientedocente',
            name='aspirante_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='Administrador.aspirante'),
        ),
        migrations.AddField(
            model_name='solicitudcambiocategoria',
            name='aspirante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='Administrador.aspirante'),
        ),
        migrations.AddField(
            model_name='actas_tribunal',
            name='solicitud_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspirante.solicitudcambiocategoria'),
        ),
    ]
