# Generated by Django 5.2 on 2025-05-15 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0001_initial'),
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actas_tribunal',
            name='miembro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_tribunal', to='RRHH.miembro_tribunal'),
        ),
    ]
