# Generated by Django 5.2 on 2025-05-10 04:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Profesor', 'Profesor'), ('Estudiante', 'Estudiante')], max_length=10, verbose_name='Tipo de aspirante')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('ci', models.CharField(max_length=11, unique=True, verbose_name='Carné de identidad')),
                ('lugar_nacimiento', models.CharField(max_length=100, verbose_name='Lugar de nacimiento')),
                ('color_piel', models.CharField(max_length=10, verbose_name='Color de piel')),
                ('estado_civil', models.CharField(max_length=10, verbose_name='Estado civil')),
                ('ciudadano', models.CharField(help_text='Solo se permiten letras y espacios', max_length=100, verbose_name='Ciudadano')),
                ('procedencia_social', models.CharField(max_length=15, verbose_name='Procedencia social')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('pais', models.CharField(help_text='Solo se permiten letras y espacios', max_length=100, verbose_name='País')),
                ('centro', models.CharField(max_length=100, verbose_name='Centro de trabajo/estudio')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('area', models.TextField(null=True)),
                ('facultad', models.CharField(max_length=100, verbose_name='Facultad')),
                ('ces', models.CharField(max_length=100, verbose_name='CES')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario')),
                ('categoria_docente', models.CharField(blank=True, max_length=10, null=True, verbose_name='Categoría docente')),
                ('fecha_otorgamiento_categoria', models.DateField(blank=True, null=True, verbose_name='Fecha de otorgamiento de categoría')),
                ('direccion', models.TextField(max_length=500, verbose_name='Dirección particular')),
                ('grado_cientifico', models.CharField(blank=True, max_length=10, null=True, verbose_name='Grado científico')),
                ('fecha_otorgamiento_grado', models.DateField(blank=True, null=True, verbose_name='Fecha de otorgamiento de grado científico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('solapin', models.CharField(max_length=50, unique=True, verbose_name='Solapín')),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aspirante',
                'verbose_name_plural': 'Aspirantes',
                'ordering': ['nombres', 'primer_apellido'],
            },
        ),
        migrations.CreateModel(
            name='RRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
