# Generated by Django 5.2 on 2025-05-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='tribunal',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
