# Generated by Django 5.2 on 2025-04-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='tipo',
            field=models.CharField(choices=[('Profesor', 'Profesor'), ('Estudiante', 'Estudiante')], max_length=10, verbose_name='Tipo de aspirante'),
        ),
    ]
