# Generated by Django 5.2 on 2025-05-17 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aspirante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='Aspirante.solicitudcambiocategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro_Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(null=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembro_chat', to='Chat.chat')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembro_chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='Chat.chat')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='Chat.miembro_chat')),
            ],
        ),
    ]
