# Generated by Django 5.2 on 2025-05-09 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrador', '0001_initial'),
        ('Aspirante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aspirante.solicitudcambiocategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro_tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.TextField()),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.aspirante')),
                ('tribunal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.tribunal')),
            ],
        ),
    ]
