# Generated by Django 5.2 on 2025-05-09 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
        ('Aspirante', '0002_alter_documentosexpedientedocente_archivo_and_more'),
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro_tribunal',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_tribunales', to='Administrador.aspirante'),
        ),
        migrations.AlterField(
            model_name='miembro_tribunal',
            name='tribunal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='RRHH.tribunal'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='solicitud_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tribunal', to='Aspirante.solicitudcambiocategoria'),
        ),
    ]
